### ISSUE TITLE
add MarshalJSON

### ISSUE THREAD

**Issue by lublak** [wk8/go-ordered-map#13]
It would be convenient if this is also implemented.

**Comment by wk8** [comment]
Shouldn't be too hard to do, and I also welcome PRs :)

Relevant parts from https://pkg.go.dev/encoding/json , first for marshalling:
> Map values encode as JSON objects. The map's key type must either be a string, an integer type, or implement encoding.TextMarshaler. The map keys are sorted and used as JSON object keys by applying the following rules, subject to the UTF-8 coercion described for string values above:
>
> *keys of any string type are used directly
> *encoding.TextMarshalers are marshaled
> *integer keys are converted to strings

And for unmarshalling:
> To unmarshal a JSON object into a map, Unmarshal first establishes a map to use. If the map is nil, Unmarshal allocates a new map. Otherwise Unmarshal reuses the existing map, keeping existing entries. Unmarshal then stores key-value pairs from the JSON object into the map. The map's key type must either be any string type, an integer, implement json.Unmarshaler, or implement encoding.TextUnmarshaler.
