### ISSUE TITLE
test_utils.go to export_test.go

### ISSUE THREAD

**Issue by yongjichen** [wk8/go-ordered-map#28]
Cause test_utils.go is just used for testing.  Could you change it to utils_test.go or export_test.go，just like the official library of Golang.  The test_utils.go will import "github.com/stretchr/testify/assert" which imports a lot of other packages.

**Comment by hesining** [comment]
https://github.com/wk8/go-ordered-map/pull/29

I try to fix this

**Comment by wk8** [comment]
Thanks for the PR, closing :)
