### ISSUE TITLE
Please bump v0.2.0 tag

### ISSUE THREAD

**Issue by SVilgelm** [wk8/go-ordered-map#3]
Hi,
Could you release a new tag please? `go get -u github.com/wk8/go-ordered-map` does not update, I had to specify the master branch  `go get -u github.com/wk8/go-ordered-map@master` in order to update :-)
like `v0.2.0`

Thank you!

**Comment by SVilgelm** [comment]
@wk8 Could you please tag a new version?

**Comment by wk8** [comment]
@SVilgelm doing today, sorry for the delay

**Comment by SVilgelm** [comment]
no worries, it's just a reminder :)

**Comment by SVilgelm** [comment]
I didn't see that you have the `.travis.yml` and it fails with last changes. I can fix it if you want :-)

**Comment by wk8** [comment]
@SVilgelm : released https://github.com/wk8/go-ordered-map/releases/tag/v0.2.0, sorry for the delay :)

**Comment by wk8** [comment]
And thanks for offering to fix builds, just did, no worries!
