### ISSUE TITLE
Umarshal not working

### ISSUE THREAD

**Issue by oq-x** [wk8/go-ordered-map#31]
```
var plistData = orderedmap.New[string, interface{}]()
_, err = plist.Unmarshal(content, &plistData)
	if err != nil {
		fmt.Println("Error parsing plist data:", err)
		return
	}
```

Error: `Error parsing plist data: plist: type mismatch: tried to decode plist type `dictionary' into value of type `*orderedmap.OrderedMap[string,interface {}]'`

**Comment by wk8** [comment]
There's tests on this: https://github.com/wk8/go-ordered-map/blob/master/json_test.go#L112, so it works for at least _some_ inputs :P

So unless you give me a specific test case where it fails, can't help you much.

**Comment by wk8** [comment]
Oh sorry read too fast. You want to parse a PLIST input? Yeah we don't support that. Should be easy to do though, I always welcome PRs.

**Comment by oq-x** [comment]
damn
