### ISSUE TITLE
Nested Maps

### ISSUE THREAD

**Issue by Jack-Drake** [wk8/go-ordered-map#35]
Dear wk8,

Thank you for this amazing project, very useful. I am having an issue with JSON Unmarshalling a json string. It seems to not be adding the json as is rather it is still randomizing it.

Anything would help.

**Comment by wk8** [comment]
Happy to have a look if you give a test case :)

**Comment by Jack-Drake** [comment]
lol I do not have a test case except a couple screenshots
![image](https://github.com/wk8/go-ordered-map/assets/44513448/d1c44a6b-2a55-46de-86bd-71576cd694fc)
![image](https://github.com/wk8/go-ordered-map/assets/44513448/2ce9b770-3288-445c-b836-34d5f3266a33)

**Comment by Jack-Drake** [comment]
and this screenshot of the struct
![image](https://github.com/wk8/go-ordered-map/assets/44513448/5ac0ff6d-2584-4af4-96b7-99fe1359d65a)

**Comment by wk8** [comment]
See https://github.com/wk8/go-ordered-map/issues/33

**Comment by Jack-Drake** [comment]
I am going to be honest I do not understand. The #33. Is the idea to make a struct for each value? such as seen below?
![image](https://github.com/wk8/go-ordered-map/assets/44513448/37af21c2-4b7b-4ccc-bea5-fc6a6ddc4cc4)

**Comment by wk8** [comment]
I don't see the connection between your ProductModel struct and the example JSON you gave.

But regardless, the gist is that if you unmarshall to an `OrderedMap[string, any]`, only the first level of your JSON object is going to be ordered. Any map contained in there are going to be regular, unordered map.

**Comment by Jack-Drake** [comment]
so what is the procedure to make sure for example that everything underneath it remains Ordered. Do i have to do the same as this picture?
(https://user-images.githubusercontent.com/44513448/264916670-37af21c2-4b7b-4ccc-bea5-fc6a6ddc4cc4.png)

**Comment by wk8** [comment]
I'm sorry, please provide an actual code snippet and an actual JSON input. Can't help you otherwise.

**Comment by Jack-Drake** [comment]
![image](https://github.com/wk8/go-ordered-map/assets/44513448/fdb050c6-2267-4576-9b6f-b8f38177af36)
Above is the json being used
`type OrderedProductModel struct {
	Description *orderedmap.OrderedMap[string, any] json:"Description"
	Note        *orderedmap.OrderedMap[string, any] json:"Note"
	Thumbnail   *orderedmap.OrderedMap[string, any] json:"Thumbnail"
	Preview     *orderedmap.OrderedMap[bool, any]  json:"Preview"
	// Size        []Sizes   `json:"Size"`
	// Options     []Options `json:"Options"`
}`
Above is the struct that should be decoding the json. This is also the one I would like to have be in order
`//parse current data into structs and maps
	data := orderedmap.New[string, ProductModel]()
	err = json.Unmarshal([]byte(jsonData), &data)
	if err != nil {
		fmt.Println("Error:", err)
		return
	}

	PrettyPrint(data)`
Above is the code I am using to parse it

**Comment by wk8** [comment]
I'm not going to re-type images into text. If you're not willing to do that yourself then sorry I can't help you.

**Comment by Jack-Drake** [comment]
lol sorry i didnt send them into text because it formatted weird. Though you just wanted to see them visually. I added them all below:

JSON:
`{
    "Business Cards": {
        "Description": "Business card printing is a service that allows you to design your own business card online. You can upload your own artwork or use one of the templates provided. You can also upload your company logo or a photo of yourself to be printed on the card. The business card is printed on a standard business card size, 3.5\" x 2\".",
        "Note": "Kindly ensure that you upload files that correspond to the dimensions selected in the Finishing Size dropdown. It's recommended to maintain a 1/8 inch margin along all edges, as this precautionary measure helps prevent inadvertent trimming during the processing phase.",
        "Thumbnail": "../assets/images/shop/img_01.jpg",
        "Preview": true,
        "Size": [
            {
                "width": 3.5,
                "height": 2
            },
            {
                "width": 2,
                "height": 3.5
            }
        ],
        "Options": [
            {
                "Paper Thickness": {
                    "14 PT": "$0",
                    "16 PT": "$0"
                },
                "Paper Type": {
                    "Glossy": "$0",
                    "Matte": "$0"
                },
                "Print On": {
                    "Single-Side": "0%",
                    "Double-Sided": "15%"  
                },
                "Quantity": {
                    "100": "$40",
                    "250": "$50",
                    "500": "$70",
                    "1000": "$90",
                    "2500": "$195",
                    "5000": "$340",
                    "10000": "$615"
                },
                "Rounded Corners": {
                    "No": "0%",
                    "Yes": "15%"
                },
                "Turnaround Time": {
                    "2-3 Business Days": "0%",
                    "Next Day": "30%",
                    "Same Day": "50%"
                }
            },
            {
                "Paper Thickness": {
                    "14 PT": "$0",
                    "16 PT": "$0"
                },
                "Paper Type": {
                    "Glossy": "$0",
                    "Matte": "$0"
                },
                "Print On": {
                    "Single-Side": "0%",
                    "Double-Sided": "15%"  
                },
                "Quantity": {
                    "100": "$40",
                    "250": "$50",
                    "500": "$70",
                    "1000": "$90",
                    "2500": "$195",
                    "5000": "$340",
                    "10000": "$615"
                },
                "Rounded Corners": {
                    "No": "0%",
                    "Yes": "15%"
                },
                "Turnaround Time": {
                    "2-3 Business Days": "0%",
                    "Next Day": "30%",
                    "Same Day": "50%"
                }
            }
        ]
    }
}`

Current Code Parsing:
`data := orderedmap.New[string, ProductModel]()
	err = json.Unmarshal([]byte(jsonData), &data)
	if err != nil {
		fmt.Println("Error:", err)
		return
	}`

Struct:
`type OrderedProductModel struct {
	Description *orderedmap.OrderedMap[string, any] json:"Description"
	Note        *orderedmap.OrderedMap[string, any] json:"Note"
	Thumbnail   *orderedmap.OrderedMap[string, any] json:"Thumbnail"
	Preview     *orderedmap.OrderedMap[bool, any]  json:"Preview"
	// Size        []Sizes   json:"Size"
	// Options     []Options json:"Options"
}`
