### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by shubham2508** [wk8/go-ordered-map#4]
Can you add a set function or an option in New() with a LRU type feature, where the order is maintained as per update?

I understand it's not the way an ordered map works but I am requesting an added functionality.
OrderedMap where the order can be defined on update also rather than only on creation.

It's not an issue but a feature request.
I can add the desired piece of code.

**Comment by wk8** [comment]
Should be pretty easy to do, but super busy at the moment. I'll try adding it when I have some time, or else I welcome pull requests ;)

**Comment by shubham2508** [comment]
Cool :) will submit a PR by the weekend

**Comment by wk8** [comment]
@shubham2508 if you still want this, https://github.com/wk8/go-ordered-map/pull/6 enabled this by adding MoveToFront. Your LRU cache would then just be an OrderedMap where you call MoveToFront on update.
