### ISSUE TITLE
Clear the ordered dict

### ISSUE THREAD

**Issue by GuyAfik** [wk8/go-ordered-map#5]
Hi,

I am not quite sure if its possible to clear the dict right now.

is it possible to implement it?

I can make a PR if necessary

**Comment by wk8** [comment]
@GuyAfik : you mean to empty it? Why not just create a new one?

**Comment by GuyAfik** [comment]
Hi @wk8.

Thanks for the quick response!

I mean to clear it out of items which is simply deleting all of its items. similiar to python for example ---> 

d = {}
d[1] = 1
d[2] = 2

d.clear() would remove all of the items.

So if I have an ordered dict with 10 items for example, I want to be able to clear it making it without items but keep the object reference.

I want to be able to keep track on the ordered map reference, so creating a new one is not a very good solution for my case.
 
Let me know your thoughts on the matter :-)

Thanks

**Comment by wk8** [comment]
I'm not sure I understand what you gain by keeping the reference instead of just creating a new one?

**Comment by GuyAfik** [comment]
alright i think the i can just create a new one in a second though so you can feel free to close it

**Comment by wk8** [comment]
Ok :) have a good day!
